### PR TITLE
Fix setup, checking if the entry_points section is present.

### LINKED ISSUE #17: tests failing?
if someone wants to point me down the path of why some of the tests are failing, i'd be interested. and could maybe help fix.

### PR DESCRIPTION
**Pull request by saimn**
When the example `[entry_points]` section from the package template is
removed from the `setup.cfg`, this breaks. Fixes #17 (cc @kelle)

### CODE REVIEW

**Comment by saimn** [comment]
Now fails on the `six` import, not sure why as six is correctly listed in the requirements:
```
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/specutils-test-2toizrgm/lib.macosx-10.7-x86_64-3.6/specutils/__init__.py", line 20, in <module>

    from .io.default_loaders import *  # noqa

  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/specutils-test-2toizrgm/lib.macosx-10.7-x86_64-3.6/specutils/io/default_loaders/tabular_fits_reader.py", line 2, in <module>

    import six

ModuleNotFoundError: No module named 'six'
```

**Comment by kelle** [comment]
Cool!  Should this fix be also made in the package template?
https://github.com/astropy/package-template/blob/master/setup.py

**Comment by nmearl** [comment]
I think the Astropy thinking is that the `[entry_points]` section should *always* be present, just have nothing under it if there are no needed entry points.

I'm inclined to follow that paradigm. @saimn We could definitely keep the if statement, but perhaps add `[entry_points]` at the end of the `setup.cfg` file?

**Comment by saimn** [comment]
I will propose the same patch to package-template. An empty `[entry_points]` should indeed work, but it's easy to avoid this kind of surprise for users of the template, and I don't think that having an empty section should be required.

**Pull request merged**
