### PR TITLE
Add stub for new spectral_resolution() method with fleshed out docstring

### PR DESCRIPTION
**Pull request by dkirkby**
See the discussion in the #spectral-resolution slack channel for background.

The goal here is to provide a uniform way to query the spectral resolution in a way that is sufficiently general to encompass any reasonable internal representation (tabulated, parameterized, sigmas, etc), but still practical for efficient computations (weighted coadds, resampling, etc).

### CODE REVIEW

**Comment by hcferguson** [comment]
If I'm understanding the docstring correctly, I think the line
```np.arange(-10,+10,201)```
should be
```np.arange(-10,+10,0.2)```

**Comment by dkirkby** [comment]
I just fixed some typos.  Thanks for checking.

**Comment by nmearl** [comment]
@dkirkby Is the intent of this PR to stay a PR until the stub has been populated, or is this stub a mental node in the broader `Spectrum1D` context that you're hoping will be fleshed out at some time in the future?

**Comment by dkirkby** [comment]
I wanted to give people a chance to comment on the API before moving forward on implementation.  Perhaps enough time has passed already?  The next step is to implement simple cases, e.g., perfect resolution and constant resolution.

**Pull request merged**
